### ISSUE TITLE
ReuseTabs with Pro Layout?

### ISSUE THREAD

**Issue by mehmetuken** [ant-design-blazor/blazor-pro-components#46]
What is the best location ReuseTabs in Pro Basic Layout?

**Comment by ElderJames** [comment]
You can replace the `@body` in the layout page.
https://github.com/ant-design-blazor/blazor-pro-components/blob/0ff24d2b50aff1e8f4ef9205287fb2d647a9b921/src/layout/example/AntDesign.ProLayout.Wasm/Shared/ProLayout.razor#L29

**Comment by aihui109** [comment]
Can tell me,How did you do it?
