### ISSUE TITLE
update for bug fix release new nuget package

### ISSUE THREAD

**Issue by wuzhenda** [ant-design-blazor/blazor-pro-components#51]
树形控件有个bug，描述如下，好像当前 0.1.10版本依然存在，能否及时更新一版没有这个bug的版本？

https://github.com/ant-design-blazor/ant-design-blazor/issues/2037

**Comment by ElderJames** [comment]
OK, this has been fixed in the component library and will be released together with the next version. In the interim you can start with the latest AntDesign nightly build.
https://github.com/ant-design-blazor/ant-design-blazor/blob/master/docs/nightly-build.zh-CN.md

**Comment by wuzhenda** [comment]
tks for reply.
