### ISSUE TITLE
How to hide right panel from pro layout

### ISSUE THREAD

**Issue by semukov** [ant-design-blazor/blazor-pro-components#52]
Hi!
How can i hide right drawing panel and right button element for settings layout?

**Comment by ElderJames** [comment]
Please delete `<SettingDrawer />` from here https://github.com/ant-design-blazor/blazor-pro-components/blob/1b41a4b5877e2be19317c196041cf8cba7862aa5/src/layout/example/AntDesign.ProLayout.Wasm/Shared/ProLayout.razor#L32

**Comment by semukov** [comment]
O, I didn't see it right away. I fiddled with the settings.
Thank you!
