### ISSUE TITLE
The pro template cannot control the folding and expansion of the left menu through variables.

### ISSUE THREAD

**Issue by HuaFangYun** [ant-design-blazor/blazor-pro-components#71]
![image](https://user-images.githubusercontent.com/30250585/228102097-06442f3a-3f33-428b-b2a3-e1b95a0b511c.png)
![image](https://user-images.githubusercontent.com/30250585/228102252-45b55b0a-1cef-4041-b94f-ea9b0c988326.png)
![image](https://user-images.githubusercontent.com/30250585/228102284-e24e51b1-9433-4f27-aeca-43f24a3679d9.png)

**Comment by yasmangera** [comment]
Facing the same problem. I think the code required is:

`            SiderWidth = Collapsed ? 48 : SiderWidth;
`
in blazor-pro-components\src\BasicLayout.razor.cs line 96. Unfortunately, couldn't create a pull request on my side for it.

**Comment by HuaFangYun** [comment]
Currently this component is a bit complicated, components within components. I think the innermost function has been realized. After setting up the fold, there should be a listener to execute the events in the inner layer. At present, only the variables are matched, but the innermost method is not supported.

**Comment by HuaFangYun** [comment]
This pro component has been rewritten by a guy. Hold on. Or you can see how to optimize this bug in this version.

**Comment by Mrzhangxiaobai2107** [comment]
问题解决了么

**Comment by Mrzhangxiaobai2107** [comment]
> 面对同样的问题。我认为所需的代码是：
> 
> ` SiderWidth = Collapsed ? 48 : SiderWidth;`in blazor-pro-components\src\BasicLayout.razor.cs第 96 行。不幸的是，无法在我这边为其创建拉取请求。
解决了么

**Comment by HuaFangYun** [comment]
问题解决了
